language: java
jdk:
  - openjdk11

# safelist
branches:
  only:
  - feat/*
  - main

jobs:
  include:
    - stage: Maven Clean
      script: mvn clean
    - stage: Maven Install
      script: mvn clean
    - stage: Unit Tests
      script: mvn test
    - stage: Checkstyle Validation
      script: mvn validate
    - stage: Docker deploy
      script: mvn deploy -Ddocker.user=user -Ddocker.password=password
        -Ddocker.url=docker-registry-url

