language: java
jdk:
  - openjdk11

services:
  - docker

before_install:
  - mvn clean
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# safelist
branches:
  only:
    - feat/**
    - main
jobs:
  include:
    - stage: Maven Install
      script: mvn install
    - stage: Unit Tests
      script: mvn test
    - stage: Checkstyle Validation
      script: mvn validate
    - stage: Test Coverage Check 75%
      script: mvn clean verify



