language: java
jdk:
  - openjdk11

# whitelist
branches:
  only:
  - feat/*
  - main

jobs:
  include:
    - stage: Maven Clean
      script: mvn clean
    - stage: Maven Install
      script: mvn clean
    - stage: Unit Tests
      script: mvn test
    - stage: Checkstyle Validation
      script: mvn validate

