language: java
jdk:
  - openjdk11
branches:
  only:
  - feat/*
  - main
services:
  - docker
before_install:
  - docker build -t twitch-analystics-service-backend .
  - docker run -d -p 8080:8080 twitch-analystics-service-backend
  - docker ps
  - docker stop 